#!/usr/bin/env bash
# This script is looping from 1 to 10 with special messages on the 4th and 8th passes
count=1
while [ "$count" -le 10 ]; do
  if [ "$count" -eq 4 ]; then
    echo "bad luck"
  elif [ "$count" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
