#!/usr/bin/env bash
# This script is displaying hours 0 to 12 with minutes 1 to 59 in each hour
hour=0
while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ "$minute" -le 59 ]; do
    echo "$minute"
    ((minute++))
  done
  ((hour++))
done
